version: '3.5'

services:
  web:
    env_file:
      - .env
    build: .
    volumes:
      - ./src:/app/src
      - ./db:/app/db
  ngrok:
    image: gtriggiano/ngrok-tunnel
    ports:
      - 4040:4040
    environment:
      TARGET_HOST: web
      TARGET_PORT: 80
    depends_on:
      - web
