version: '3.5'

services:
  web:
    env_file:
      - .env
    build:
      dockerfile: docker/web/Dockerfile
      context: ./
    ports:
      - 8999:80
      - 4444:4444
    volumes:
      - ./src:/app/src
      - ./codeception.yml:/app/codeception.yml
      - ./tests:/app/tests
