version: '3.5'

services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - 8999:80
    volumes:
      - ./src:/app/src
      - ../favicon-32x32.webp:/app/src/public/favicon-32x32.webp
